version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    filters:
      branches:
        only: circleci
    steps:
      - checkout
      - run:
          name: Setup System Dependencies
          command: apt-get update && apt-get install gcc g++ make curl wget clang -y
      - run:
          name: Build ispc-rs
          command: ./.circleci/build-ispc-rs-linux.sh

